package com.apps.therapassignment.model

data class Others(
    val Audio power output: String,
    val Auto Motion Plus: String,
    val Bezel Type: String,
    val Bluetooth: String,
    val Color: String,
    val Colour Enhancement: String,
    val Contrast Enhancement: String,
    val DOLBY AUDIO FORMAT SUPPORT: String,
    val Design: String,
    val Dimension: String,
    val Dimensions ( W x Hx D ): String,
    val Display: String,
    val Dolby Atmos: String,
    val Film Mode: String,
    val Micro Dimming: String,
    val On/off timer: String,
    val Picture Engine: String,
    val Picture Processor: String,
    val Power Consumption: String,
    val Power Requirements: String,
    val Power Supply: String,
    val Q-Symphony: String,
    val Series: String,
    val Set Size without Stand (WxHxD): String,
    val Sleep timer: String,
    val Speakers: String,
    val Storage: String,
    val TV to Mobile - Mirroring: String,
    val Voice Search: String,
    val Web Browser: String,
    val •Dimensions (L x W x H): String
)